/**
 * composition.ts
 * Interview question composition rules.
 * Selects and orders questions to maximize coverage and value.
 */

import type { Competency } from '../schemas/competency.js';
import { importanceWeight, strengthValue } from '../scoring/strength-rules.js';

export interface QuestionCandidate {
  kind: 'behavioral' | 'role_specific' | 'evidence_gap';
  competencyIds: string[];
  question: string;
  score: number; // Selection priority score
}

/**
 * Select best questions from candidates generated by the model.
 *
 * Strategy:
 * - Model generates 6 candidates: 3 behavioral, 3 role-specific
 * - Server keeps 2 of each, choosing those whose competencies score highest
 *   on: w × (1 − s) + priorityBonus
 * - This maximizes interview value by targeting important, under-evidenced areas
 *
 * Returns: { behavioral: Question[], roleSpecific: Question[] }
 */
export function selectQuestions(
  behavioralCandidates: Omit<QuestionCandidate, 'score'>[],
  roleSpecificCandidates: Omit<QuestionCandidate, 'score'>[],
  competenciesById: Map<string, Competency>
): {
  behavioral: QuestionCandidate[];
  roleSpecific: QuestionCandidate[];
} {
  // Score and sort behavioral candidates
  const scoredBehavioral = behavioralCandidates
    .map((q) => ({
      ...q,
      score: calculateQuestionScore(q.competencyIds, competenciesById),
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 2);

  // Score and sort role-specific candidates
  const scoredRoleSpecific = roleSpecificCandidates
    .map((q) => ({
      ...q,
      score: calculateQuestionScore(q.competencyIds, competenciesById),
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, 2);

  return {
    behavioral: scoredBehavioral,
    roleSpecific: scoredRoleSpecific,
  };
}

/**
 * Calculate question selection score based on targeted competencies.
 * Score = w × (1 − s) + priorityBonus
 *
 * Higher scores for:
 * - Important competencies (higher w)
 * - Under-evidenced competencies (lower s)
 * - User-prioritized competencies (interviewPriority flag)
 */
function calculateQuestionScore(
  competencyIds: string[],
  competenciesById: Map<string, Competency>
): number {
  let totalScore = 0;

  for (const id of competencyIds) {
    const comp = competenciesById.get(id);
    if (!comp) continue;

    const w = importanceWeight(comp.importance);
    const s = strengthValue(comp.strength);
    const priorityBonus = comp.interviewPriority ? 2 : 0;

    totalScore += w * (1 - s) + priorityBonus;
  }

  return totalScore;
}

/**
 * Generate the evidence-gap question.
 * Targets the competency with highest w × (1 − s), with ties broken by interviewPriority.
 *
 * Returns the competency ID to target for the gap question.
 */
export function selectEvidenceGapTarget(competencies: Competency[]): string | null {
  if (competencies.length === 0) return null;

  let bestCompetency: Competency | null = null;
  let bestScore = -1;

  for (const comp of competencies) {
    const w = importanceWeight(comp.importance);
    const s = strengthValue(comp.strength);
    const priorityBonus = comp.interviewPriority ? 10 : 0;
    const score = w * (1 - s) + priorityBonus;

    if (score > bestScore) {
      bestScore = score;
      bestCompetency = comp;
    }
  }

  return bestCompetency?.id || null;
}

/**
 * Order selected questions into the final interview plan.
 * Order: B1, R1, GAP, B2, R2
 */
export function orderQuestions(
  behavioral: QuestionCandidate[],
  roleSpecific: QuestionCandidate[],
  gapQuestion: { competencyIds: string[]; question: string }
): QuestionCandidate[] {
  const questions: QuestionCandidate[] = [];

  if (behavioral[0]) questions.push(behavioral[0]);
  if (roleSpecific[0]) questions.push(roleSpecific[0]);
  questions.push({ kind: 'evidence_gap' as const, ...gapQuestion, score: 0 });
  if (behavioral[1]) questions.push(behavioral[1]);
  if (roleSpecific[1]) questions.push(roleSpecific[1]);

  return questions;
}
