/**
 * limits.ts
 * Single source of truth for all input/output/quota limits.
 * Used by validation, UI, and backend quota enforcement.
 */

export const LIMITS = {
  // Input limits
  RESUME_TEXT_MAX_CHARS: 12_000,
  RESUME_TEXT_MIN_CHARS: 200,
  JOB_DESCRIPTION_MAX_CHARS: 8_000,
  JOB_DESCRIPTION_MIN_CHARS: 100,
  COMPANY_NAME_MAX_CHARS: 100,
  ROLE_TITLE_MAX_CHARS: 100,

  // Resume upload
  RESUME_PDF_MAX_SIZE_BYTES: 5 * 1024 * 1024, // 5 MB

  // Evidence and competencies
  COMPETENCIES_MIN: 6,
  COMPETENCIES_MAX: 12,
  EVIDENCE_QUOTE_MIN_CHARS: 12, // For grounding verification
  EVIDENCE_QUOTE_MAX_CHARS: 500,
  RECOMMENDATION_MAX: 8,

  // Interview
  INTERVIEW_QUESTIONS_PRIMARY: 5,
  INTERVIEW_FOLLOWUPS_MAX: 2,
  ANSWER_TEXT_MIN_CHARS: 20,
  ANSWER_TEXT_MAX_CHARS: 2_000,
  FOLLOW_UP_QUESTION_MAX_CHARS: 300,

  // Audio recording
  AUDIO_MAX_SIZE_BYTES: 10 * 1024 * 1024, // 10 MB
  AUDIO_MAX_DURATION_SECONDS: 120, // 2 minutes per answer

  // Model output limits (stricter than stored limits)
  MODEL_COMPETENCY_NAME_MAX_CHARS: 80,
  MODEL_COMPETENCY_DESC_MAX_CHARS: 200,
  MODEL_MISSING_EVIDENCE_MAX_CHARS: 150,
  MODEL_SUGGESTION_MAX_CHARS: 180,
  MODEL_RECOMMENDATION_REASON_MAX_CHARS: 200,
  MODEL_EVALUATION_RATIONALE_MAX_CHARS: 300,
  MODEL_EVALUATION_STRENGTH_MAX_CHARS: 300,
  MODEL_EVALUATION_IMPROVEMENT_MAX_CHARS: 300,
  MODEL_STRONGER_OUTLINE_POINTS: 3,
  MODEL_STRONGER_OUTLINE_POINT_MAX_CHARS: 150,
  MODEL_QUESTION_MAX_CHARS: 250,

  // Report
  REPORT_NARRATIVE_MAX_CHARS: 2_000,

  // Quotas (per session)
  QUOTA_ANALYSIS_ATTEMPTS: 3,
  QUOTA_CONFIRMATIONS: 10,
  QUOTA_RECOMMENDATION_DECISIONS: 30,
  QUOTA_INTERVIEW_GENERATIONS: 3,
  QUOTA_EVALUATIONS: 15, // 5 primary + up to 2 follow-ups each + practice
  QUOTA_PRACTICE_ATTEMPTS: 10,
  QUOTA_REPORT_GENERATIONS: 3,
  QUOTA_TRANSCRIPTIONS: 10,

  // Quotas (per IP, per hour)
  QUOTA_SESSIONS_PER_IP_HOUR: 5,

  // Global budgets (per day)
  GLOBAL_BEDROCK_CALLS_PER_DAY: 500,
  GLOBAL_TRANSCRIBE_MINUTES_PER_DAY: 60,

  // Bedrock token limits
  BEDROCK_ANALYSIS_MAX_TOKENS: 3_000,
  BEDROCK_CONFIRM_REWRITE_MAX_TOKENS: 400,
  BEDROCK_QUESTIONS_MAX_TOKENS: 1_000,
  BEDROCK_EVALUATION_MAX_TOKENS: 800,
  BEDROCK_REPORT_MAX_TOKENS: 1_200,

  // TTL
  SESSION_TTL_HOURS: 24,
  IP_RATE_LIMIT_TTL_HOURS: 2,
  GLOBAL_BUDGET_TTL_DAYS: 3,

  // Parsing
  PARSEABILITY_MIN_WORD_COUNT: 300,
  PARSEABILITY_MAX_WORD_COUNT: 1_200,
  PARSEABILITY_MAX_GARBLED_RATIO: 0.02, // 2%
} as const;

export type Limits = typeof LIMITS;
